### ISSUE TITLE
integration with magedelight onestepcheckout

### ISSUE THREAD

**Issue by yohanespradono** [ideal-postcodes/magento#493]
Hi,

Apparently this doesn't support magedelight onestepcheckout. What element it tries to attach to?

Thank you

**Comment by cblanc** [comment]
@mfilip  will follow up on this tomorrow

**Comment by mfilip** [comment]
@yohanespradono can  you provide more information how you trying to setup our extension. There is functionality in our extension that allows to configure it for custom solutions like your onestepcheckout. In such situation advanced configuration coming handy. For your situation you can  try to use "Custom Fields Configuration" in that section to provide your address fields selectors like:
`[{
 "line_1":"#line_1",
 "line_2":"#line_2",
 "line_3":"#line_3",
 "postcode":"#postcode",
 "post_town":"#post_town",
 "county":"#county",
 "country":"#country",
 "organisation_name":"#organisation_name"
}]`

You can configure multiple custom forms on your Magento frontend/backend. You may provide any valid CSS selector that allow to match single element of form for each address line. Note that if your form do not have all fields just skip them in configuration because require once are line_1 and country in order to bind solution UK addresses.



Let us know if you managed to setup it or had problems with it
